### ISSUE TITLE
Decide max length for different parts of protocol messages. Implement.

### ISSUE THREAD

**Issue by hukkin** [jjaanila/mChat#14]
Currently only length for the whole protocol message is specified.

**Comment by jjaanila** [comment]
Implemented to client in e5c6393ab14e2641a9fc2bc1718e606a1e2b278b..

**Comment by hukkin** [comment]
So the final max lengths are: 
PROTOCOL_MSG_MAXLEN = 1024
NICKNAME_MAXLEN = 32
CHANNELNAME_MAXLEN = 64

Note that the server will check for CHANNELNAME_MAXLEN in PART and JOIN messages in addition to MSG messages.

**Comment by hukkin** [comment]
Implemented in server in commit 9bb8f4c. Close this issue when implemented in client in PART and JOIN messages.
