### ISSUE TITLE
Plan and implement private channels

### ISSUE THREAD

**Issue by hukkin** [jjaanila/mChat#15]
If we do this, I suggest we implement this only in the client, so that it works in the following way:
1. Start the client and connect to server.
2. type "joinprivate some_private_channel password"
3. The client makes a string of the private channel name and password. It then uses some hash function to calculate a hash from this string.
4. The client then actually joins a channel that has the name of the hash function return value.
5. The client can send messages to the channel e.g. by typing "msgprivate some_private_channel message_content".

Therefore the user never has to deal with the actual name of the private channel (a cryptic hash function return value).

Any comments to this solution? Any other ideas?

**Comment by hukkin** [comment]
Problems with the approach explained above:
- there can be multiple private channels with the same channel name if the passwords are different
- the user can not know if he/she typed password correctly

**Comment by hukkin** [comment]
Both problems could be fixed by changing the server so, that on every JOIN request by a client, the server would make a query to other servers asking if a channel with that channel name already exists. This means more work for us.

**Comment by jjaanila** [comment]
We could add a join notification from server to clients. When a client joins a channel, the server sends a MSG with a special nick (e.g. SYSTEM) to that channel. This is quite simple to implement and requires modifications only to server. Nick SYSTEM could be prohibited already in client though.
