### ISSUE TITLE
Nickname length and channel name length are checked in UTF-8 character length

### ISSUE THREAD

**Issue by hukkin** [jjaanila/mChat#16]
The lengths should be checked in number of bytes.

**Comment by jjaanila** [comment]
Check IRC..

**Comment by hukkin** [comment]
So what is the final verdict on this one. I say that we keep all the same lengths (protocol msg 1024, channel name 64, nickname 32) but say that those are the number of UTF-8 encoded characters. So the theoretical maximum length of a protocol message is actually 1024 \* 4. Any other opinions?

**Comment by hukkin** [comment]
My explanation in the previous message is the new specification and both the server and client should now be following it.
