### ISSUE TITLE
Server does not forward system messages to other servers

### ISSUE THREAD

**Issue by hukkin** [jjaanila/mChat#17]
Also, I would prefer an implementation for system messages that uses a separate protocol message instead of occupying the nick SYSTEM.

**Comment by hukkin** [comment]
Should be fixed in server. Test this when client is up to date with the latest spec.

**Comment by jjaanila** [comment]
JOIN messages are not forwarded currently from a server to another. The server does not even send the SYSTEM message to the client who issued the JOIN if there is another server connected. PART messages and their SYSTEM messages seemed to work though.

**Comment by hukkin** [comment]
What about now?

**Comment by hukkin** [comment]
It works!
