### ISSUE TITLE
Normal MSG messages don't go from client to client using the latest client source

### ISSUE THREAD

**Issue by hukkin** [jjaanila/mChat#21]
Steps to reproduce:
1. Connect two clients to server
2. Join the same channel
3. Send a message

Result:
The other client doesnt receive the message.

I think this is due to changes in client source because it all works good when using older source for client (e.g. commit 78752e1)

**Comment by hukkin** [comment]
Janne: "It seems that JOIN is failing at the server end: self.channels.join(sock, channel) on line 187 in server.py. This also breaks MSGs."

What makes you think this? Seems to be working for me after the last commit... Close this if you don't see any issue anymore.

**Comment by jjaanila** [comment]
After reinspection, it seems to work.
