### ISSUE TITLE
Client doesn't implement correct heartbleed protocol

### ISSUE THREAD

**Issue by hukkin** [jjaanila/mChat#3]
The new protocol is:
request message that client receives: HEART\n
response message that client has to respond: BLEED\n

Client does not need to worry about timing. Just respond to server when the server asks for it.

The client can also ping the server with HEART\n messages to make sure server is up, but that is up to client implementation.

**Comment by jjaanila** [comment]
Implemented in commit ac9abf6ddc60591f6a28a1863d308811d0b3993c.
